version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run:
          name: PWD
          command: pwd
      - run:
          name: Show Directory
          command: ls
      - run:
          name: Version
          command: clang --version
      - run:
          name: Is brew installed
          command: brew update
      - run:
          name: variables
          command: set
