version: 2
jobs:
  build:
    docker:
      - image: julia
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print version
          command: |
            which julia
            julia --version
